using Npgsql;

var app = WebApplication.CreateBuilder(args).Build();
var cs = Environment.GetEnvironmentVariable("DATABASE_URL") ?? throw new InvalidOperationException("DATABASE_URL não configurada");

await SharedApi.Initialize(cs, """
CREATE SCHEMA IF NOT EXISTS air_quality;
CREATE TABLE IF NOT EXISTS air_quality.stations(id TEXT PRIMARY KEY,name TEXT NOT NULL,area_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS air_quality.sensors(id TEXT PRIMARY KEY,station_id TEXT NOT NULL REFERENCES air_quality.stations(id),owner_name TEXT NOT NULL,description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS air_quality.particulate_readings(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES air_quality.stations(id),
 sensor_id TEXT NOT NULL REFERENCES air_quality.sensors(id),area_id TEXT NOT NULL,pm25 DOUBLE PRECISION NOT NULL,
 pm10 DOUBLE PRECISION,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS air_quality.gas_readings(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES air_quality.stations(id),
 sensor_id TEXT NOT NULL REFERENCES air_quality.sensors(id),area_id TEXT NOT NULL,co_ppm DOUBLE PRECISION,no3_ug_m3 DOUBLE PRECISION,
 co2_ppm DOUBLE PRECISION,o2_percent DOUBLE PRECISION,tvoc_ppb DOUBLE PRECISION,measured_at TIMESTAMPTZ NOT NULL,
 received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS air_quality.environment_readings(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES air_quality.stations(id),
 sensor_id TEXT NOT NULL REFERENCES air_quality.sensors(id),area_id TEXT NOT NULL,temperature_c DOUBLE PRECISION NOT NULL,
 humidity_percent DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS air_quality.alerts(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reading_type TEXT NOT NULL,reading_id BIGINT NOT NULL,
 severity TEXT NOT NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),UNIQUE(reading_type,reading_id,message));
INSERT INTO air_quality.stations VALUES('station-central','Estação Central','area-central') ON CONFLICT DO NOTHING;
INSERT INTO air_quality.sensors VALUES
 ('japa-air-01','station-central','Japa','PM2.5, CO, NO3 e meteorologia'),
 ('mat-air-01','station-central','Mat','PM2.5, PM10, NO3, TVOC, CO2 e O2'),
 ('tanke-air-01','station-central','Tanke','PM2.5, PM10, NO3, TVOC, CO2 e O2')
 ON CONFLICT DO NOTHING;
""");

app.MapPost("/api/v1/air-quality/particulate", async (ParticulateInput p) =>
{
    if (p.Pm25 < 0 || p.Pm10 < 0) return Results.BadRequest(new { erro = "PM2.5 e PM10 não podem ser negativos" });
    try
    {
        var saved = await SharedApi.Insert(cs, "air_quality.particulate_readings", new Dictionary<string, object?> {
            ["station_id"]=p.StationId,["sensor_id"]=p.SensorId,["area_id"]=p.AreaId,["pm25"]=p.Pm25,["pm10"]=p.Pm10,["measured_at"]=p.Timestamp }, p);
        if (saved.Inserted && (p.Pm25 >= 35 || p.Pm10 >= 50))
            await AddAlert("particulate", saved.Id, p.Pm25 >= 75 ? "high" : "medium", "Concentração elevada de material particulado");
        return saved.Inserted ? Results.Created($"/api/v1/air-quality/particulate/{saved.Id}", new { id=saved.Id,status="persisted" }) : Results.Ok(new { id=saved.Id,status="already received" });
    }
    catch (PostgresException e) when (e.SqlState == "23503") { return Results.BadRequest(new { erro = "StationId ou SensorId não cadastrado" }); }
});
app.MapPost("/api/v1/air-quality/gases", async (GasInput p) =>
{
    if (new double?[] {p.CoPpm,p.No3UgM3,p.Co2Ppm,p.O2Percent,p.TvocPpb}.All(v => v is null))
        return Results.BadRequest(new { erro = "Informe ao menos uma medição de gás" });
    try
    {
        var saved = await SharedApi.Insert(cs, "air_quality.gas_readings", new Dictionary<string, object?> {
            ["station_id"]=p.StationId,["sensor_id"]=p.SensorId,["area_id"]=p.AreaId,["co_ppm"]=p.CoPpm,["no3_ug_m3"]=p.No3UgM3,
            ["co2_ppm"]=p.Co2Ppm,["o2_percent"]=p.O2Percent,["tvoc_ppb"]=p.TvocPpb,["measured_at"]=p.Timestamp }, p);
        if (saved.Inserted && (p.Co2Ppm >= 1000 || p.TvocPpb >= 500))
            await AddAlert("gases", saved.Id, "medium", "Concentração elevada de gases");
        return saved.Inserted ? Results.Created($"/api/v1/air-quality/gases/{saved.Id}", new { id=saved.Id,status="persisted" }) : Results.Ok(new { id=saved.Id,status="already received" });
    }
    catch (PostgresException e) when (e.SqlState == "23503") { return Results.BadRequest(new { erro = "StationId ou SensorId não cadastrado" }); }
});
app.MapPost("/api/v1/air-quality/environment", async (EnvironmentInput p) =>
{
    if (p.HumidityPercent is < 0 or > 100 || p.TemperatureC is < -100 or > 100)
        return Results.BadRequest(new { erro = "Temperatura ou umidade fora da faixa aceita" });
    try
    {
        var saved = await SharedApi.Insert(cs, "air_quality.environment_readings", new Dictionary<string, object?> {
            ["station_id"]=p.StationId,["sensor_id"]=p.SensorId,["area_id"]=p.AreaId,["temperature_c"]=p.TemperatureC,
            ["humidity_percent"]=p.HumidityPercent,["measured_at"]=p.Timestamp }, p);
        return saved.Inserted ? Results.Created($"/api/v1/air-quality/environment/{saved.Id}", new { id=saved.Id,status="persisted" }) : Results.Ok(new { id=saved.Id,status="already received" });
    }
    catch (PostgresException e) when (e.SqlState == "23503") { return Results.BadRequest(new { erro = "StationId ou SensorId não cadastrado" }); }
});

app.MapGet("/api/v1/air-quality/particulate", (int? limit) => SharedApi.Query(cs, "SELECT * FROM air_quality.particulate_readings ORDER BY id DESC LIMIT @limit", ("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/air-quality/gases", (int? limit) => SharedApi.Query(cs, "SELECT * FROM air_quality.gas_readings ORDER BY id DESC LIMIT @limit", ("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/air-quality/environment", (int? limit) => SharedApi.Query(cs, "SELECT * FROM air_quality.environment_readings ORDER BY id DESC LIMIT @limit", ("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/air-quality/sensors", () => SharedApi.Query(cs, "SELECT * FROM air_quality.sensors ORDER BY id"));
app.MapGet("/api/v1/air-quality/stations", () => SharedApi.Query(cs, "SELECT * FROM air_quality.stations ORDER BY id"));
app.MapGet("/api/v1/air-quality/sensors/{id}/readings", (string id, int? limit) => SharedApi.Query(cs, Combined("sensor_id"), ("id",id),("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/air-quality/stations/{id}/readings", (string id, int? limit) => SharedApi.Query(cs, Combined("station_id"), ("id",id),("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/air-quality/areas/{id}/average", (string id) => SharedApi.Query(cs, """
 SELECT @id area_id,
 (SELECT avg(pm25) FROM air_quality.particulate_readings WHERE area_id=@id) avg_pm25,
 (SELECT avg(pm10) FROM air_quality.particulate_readings WHERE area_id=@id) avg_pm10,
 (SELECT avg(co2_ppm) FROM air_quality.gas_readings WHERE area_id=@id) avg_co2_ppm,
 (SELECT avg(tvoc_ppb) FROM air_quality.gas_readings WHERE area_id=@id) avg_tvoc_ppb,
 (SELECT avg(temperature_c) FROM air_quality.environment_readings WHERE area_id=@id) avg_temperature_c,
 (SELECT avg(humidity_percent) FROM air_quality.environment_readings WHERE area_id=@id) avg_humidity_percent
 """,("id",id)));
app.MapGet("/api/v1/air-quality/alerts", (int? limit) => SharedApi.Query(cs, "SELECT * FROM air_quality.alerts ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit))));
app.MapGet("/", () => Results.Redirect("/api/v1/air-quality/stations"));
app.MapGet("/health/live", () => Results.Ok(new { status="live" }));
app.MapGet("/health/ready", () => SharedApi.Ready(cs,"air_quality"));
app.Run("http://0.0.0.0:" + (Environment.GetEnvironmentVariable("PORT") ?? "3001"));

async Task AddAlert(string type,long id,string severity,string message)
{
    await using var connection = new NpgsqlConnection(cs); await connection.OpenAsync();
    await using var command = connection.CreateCommand();
    command.CommandText="INSERT INTO air_quality.alerts(reading_type,reading_id,severity,message) VALUES(@type,@id,@severity,@message) ON CONFLICT DO NOTHING";
    command.Parameters.AddWithValue("type",type);command.Parameters.AddWithValue("id",id);command.Parameters.AddWithValue("severity",severity);command.Parameters.AddWithValue("message",message);
    await command.ExecuteNonQueryAsync();
}
static string Combined(string field) => $"""
 SELECT * FROM (
  SELECT id,'particulate' reading_type,station_id,sensor_id,area_id,measured_at,to_jsonb(p)-'payload_hash' data FROM air_quality.particulate_readings p WHERE {field}=@id
  UNION ALL SELECT id,'gases',station_id,sensor_id,area_id,measured_at,to_jsonb(g)-'payload_hash' FROM air_quality.gas_readings g WHERE {field}=@id
  UNION ALL SELECT id,'environment',station_id,sensor_id,area_id,measured_at,to_jsonb(e)-'payload_hash' FROM air_quality.environment_readings e WHERE {field}=@id
 ) readings ORDER BY measured_at DESC LIMIT @limit
 """;

record ParticulateInput(string StationId,string SensorId,string AreaId,double Pm25,double? Pm10,DateTimeOffset Timestamp);
record GasInput(string StationId,string SensorId,string AreaId,double? CoPpm,double? No3UgM3,double? Co2Ppm,double? O2Percent,double? TvocPpb,DateTimeOffset Timestamp);
record EnvironmentInput(string StationId,string SensorId,string AreaId,double TemperatureC,double HumidityPercent,DateTimeOffset Timestamp);
