using Npgsql;

var app=WebApplication.CreateBuilder(args).Build();
var cs=Environment.GetEnvironmentVariable("DATABASE_URL")??throw new InvalidOperationException("DATABASE_URL não configurada");
await SharedApi.Initialize(cs,"""
CREATE SCHEMA IF NOT EXISTS thermal_inversion;
CREATE TABLE IF NOT EXISTS thermal_inversion.stations(id TEXT PRIMARY KEY,name TEXT NOT NULL,area_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS thermal_inversion.sensors(id TEXT PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),owner_name TEXT NOT NULL,description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS thermal_inversion.temperature_profiles(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),surface_sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),upper_sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),surface_temperature_c DOUBLE PRECISION NOT NULL,upper_temperature_c DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS thermal_inversion.soil_moisture_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),soil_moisture_percent DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS thermal_inversion.air_humidity_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),air_humidity_percent DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS thermal_inversion.atmospheric_pressure_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),pressure_hpa DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS thermal_inversion.wind_speed_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),sensor_id TEXT NOT NULL REFERENCES thermal_inversion.sensors(id),wind_speed_mps DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS thermal_inversion.alerts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reading_type TEXT NOT NULL,reading_id BIGINT NOT NULL,severity TEXT NOT NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),UNIQUE(reading_type,reading_id,message));
CREATE TABLE IF NOT EXISTS thermal_inversion.occurrences(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id TEXT NOT NULL REFERENCES thermal_inversion.stations(id),description TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',occurred_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp());
INSERT INTO thermal_inversion.stations VALUES('station-central','Estação Térmica Central','area-central') ON CONFLICT DO NOTHING;
INSERT INTO thermal_inversion.sensors VALUES
 ('japa-surface-01','station-central','Japa','Temperatura da superfície'),('japa-upper-01','station-central','Japa','Temperatura superior'),
 ('japa-thermal-01','station-central','Japa','Umidade, pressão, solo e vento'),
 ('mat-surface-01','station-central','Mat','Temperatura da superfície'),('mat-upper-01','station-central','Mat','Temperatura superior'),
 ('mat-thermal-01','station-central','Mat','Umidade, pressão, solo e vento'),
 ('tanke-surface-01','station-central','Tanke','Temperatura da superfície'),('tanke-upper-01','station-central','Tanke','Temperatura superior'),
 ('tanke-thermal-01','station-central','Tanke','Umidade, pressão, solo e vento')
 ON CONFLICT DO NOTHING;
""");

app.MapPost("/api/v1/thermal-inversion/temperature-profile",async(TemperatureProfileInput p)=>{
 if(p.SurfaceTemperatureC is < -100 or > 100||p.UpperTemperatureC is < -100 or > 100)return Results.BadRequest(new{erro="Temperatura fora da faixa aceita"});
 try{
  var saved=await SharedApi.Insert(cs,"thermal_inversion.temperature_profiles",new Dictionary<string,object?>{{"station_id",p.StationId},{"surface_sensor_id",p.SurfaceSensorId},{"upper_sensor_id",p.UpperSensorId},{"surface_temperature_c",p.SurfaceTemperatureC},{"upper_temperature_c",p.UpperTemperatureC},{"measured_at",p.Timestamp}},p);
  var delta=p.UpperTemperatureC-p.SurfaceTemperatureC;
  if(saved.Inserted&&delta>0)await Alert("temperature-profile",saved.Id,delta>=5?"high":delta>=2?"medium":"low",$"Inversão térmica detectada: diferença de {delta:F1} °C");
  return Response(saved,"temperature-profile");
 }catch(PostgresException e)when(e.SqlState=="23503"){return Results.BadRequest(new{erro="StationId ou sensores não cadastrados"});}
});
app.MapPost("/api/v1/thermal-inversion/soil-moisture",(SoilMoistureInput p)=>SaveSingle("soil_moisture_readings","soil_moisture_percent","soil-moisture",p.StationId,p.SensorId,p.SoilMoisturePercent,p.Timestamp,p.SoilMoisturePercent<=20,"Umidade do solo baixa",true));
app.MapPost("/api/v1/thermal-inversion/air-humidity",(AirHumidityInput p)=>SaveSingle("air_humidity_readings","air_humidity_percent","air-humidity",p.StationId,p.SensorId,p.AirHumidityPercent,p.Timestamp,p.AirHumidityPercent<=20,"Umidade do ar baixa",true));
app.MapPost("/api/v1/thermal-inversion/atmospheric-pressure",(AtmosphericPressureInput p)=>SaveSingle("atmospheric_pressure_readings","pressure_hpa","atmospheric-pressure",p.StationId,p.SensorId,p.PressureHpa,p.Timestamp,false,"",false));
app.MapPost("/api/v1/thermal-inversion/wind-speed",(WindSpeedInput p)=>SaveSingle("wind_speed_readings","wind_speed_mps","wind-speed",p.StationId,p.SensorId,p.WindSpeedMps,p.Timestamp,p.WindSpeedMps<=1.5,"Velocidade do vento baixa",false));
app.MapPost("/api/v1/thermal-inversion/occurrences",async(OccurrenceInput p)=>{
 await using var connection=new NpgsqlConnection(cs);await connection.OpenAsync();await using var command=connection.CreateCommand();
 command.CommandText="INSERT INTO thermal_inversion.occurrences(station_id,description,severity,status,occurred_at) VALUES(@station,@description,@severity,@status,@date) RETURNING id";
 command.Parameters.AddWithValue("station",p.StationId);command.Parameters.AddWithValue("description",p.Description);command.Parameters.AddWithValue("severity",p.Severity);command.Parameters.AddWithValue("status",p.Status);command.Parameters.AddWithValue("date",p.Timestamp.ToUniversalTime());
 try{var id=(long)(await command.ExecuteScalarAsync())!;return Results.Created($"/api/v1/thermal-inversion/occurrences/{id}",new{id,status="persisted"});}
 catch(PostgresException e)when(e.SqlState=="23503"){return Results.BadRequest(new{erro="StationId não cadastrado"});}
});

app.MapGet("/api/v1/thermal-inversion/temperature-profile",(int? limit)=>List("temperature_profiles",limit));
app.MapGet("/api/v1/thermal-inversion/soil-moisture",(int? limit)=>List("soil_moisture_readings",limit));
app.MapGet("/api/v1/thermal-inversion/air-humidity",(int? limit)=>List("air_humidity_readings",limit));
app.MapGet("/api/v1/thermal-inversion/atmospheric-pressure",(int? limit)=>List("atmospheric_pressure_readings",limit));
app.MapGet("/api/v1/thermal-inversion/wind-speed",(int? limit)=>List("wind_speed_readings",limit));
app.MapGet("/api/v1/thermal-inversion/stations",()=>SharedApi.Query(cs,"SELECT * FROM thermal_inversion.stations ORDER BY id"));
app.MapGet("/api/v1/thermal-inversion/sensors",()=>SharedApi.Query(cs,"SELECT * FROM thermal_inversion.sensors ORDER BY id"));
app.MapGet("/api/v1/thermal-inversion/stations/{id}/readings",(string id,int? limit)=>SharedApi.Query(cs,Combined(),("id",id),("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/thermal-inversion/stations/{id}/latest",(string id)=>SharedApi.Query(cs,Combined(),("id",id),("limit",5)));
app.MapGet("/api/v1/thermal-inversion/areas/{id}/thermal-profile",(string id,int? limit)=>SharedApi.Query(cs,"SELECT p.*,p.upper_temperature_c-p.surface_temperature_c delta_temperature_c,(p.upper_temperature_c>p.surface_temperature_c) inversion_detected FROM thermal_inversion.temperature_profiles p JOIN thermal_inversion.stations s ON s.id=p.station_id WHERE s.area_id=@id ORDER BY p.measured_at DESC LIMIT @limit",("id",id),("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/thermal-inversion/alerts",(int? limit)=>SharedApi.Query(cs,"SELECT * FROM thermal_inversion.alerts ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/thermal-inversion/occurrences",(int? limit)=>SharedApi.Query(cs,"SELECT * FROM thermal_inversion.occurrences ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit))));
app.MapGet("/",()=>Results.Redirect("/api/v1/thermal-inversion/stations"));
app.MapGet("/health/live",()=>Results.Ok(new{status="live"}));
app.MapGet("/health/ready",()=>SharedApi.Ready(cs,"thermal_inversion"));
app.Run("http://0.0.0.0:"+(Environment.GetEnvironmentVariable("PORT")??"3003"));

async Task<IResult> SaveSingle(string table,string column,string type,string station,string sensor,double value,DateTimeOffset timestamp,bool alert,string message,bool percentage)
{
 if(value<0||(percentage&&value>100))return Results.BadRequest(new{erro="Valor fora da faixa aceita"});
 try{
  var saved=await SharedApi.Insert(cs,$"thermal_inversion.{table}",new Dictionary<string,object?>{{"station_id",station},{"sensor_id",sensor},{column,value},{"measured_at",timestamp}},new{type,station,sensor,value,timestamp});
  if(saved.Inserted&&alert)await Alert(type,saved.Id,"medium",message);
  return Response(saved,type);
 }catch(PostgresException e)when(e.SqlState=="23503"){return Results.BadRequest(new{erro="StationId ou SensorId não cadastrado"});}
}
IResult Response((long Id,bool Inserted) saved,string type)=>saved.Inserted?Results.Created($"/api/v1/thermal-inversion/{type}/{saved.Id}",new{id=saved.Id,status="persisted"}):Results.Ok(new{id=saved.Id,status="already received"});
async Task Alert(string type,long id,string severity,string message){await using var connection=new NpgsqlConnection(cs);await connection.OpenAsync();await using var command=connection.CreateCommand();command.CommandText="INSERT INTO thermal_inversion.alerts(reading_type,reading_id,severity,message) VALUES(@type,@id,@severity,@message) ON CONFLICT DO NOTHING";command.Parameters.AddWithValue("type",type);command.Parameters.AddWithValue("id",id);command.Parameters.AddWithValue("severity",severity);command.Parameters.AddWithValue("message",message);await command.ExecuteNonQueryAsync();}
Task<List<System.Text.Json.JsonElement>> List(string table,int? limit)=>SharedApi.Query(cs,$"SELECT * FROM thermal_inversion.{table} ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit)));
static string Combined()=>"""
 SELECT * FROM (
  SELECT id,'temperature-profile' reading_type,station_id,measured_at,to_jsonb(p)-'payload_hash' data FROM thermal_inversion.temperature_profiles p WHERE station_id=@id
  UNION ALL SELECT id,'soil-moisture',station_id,measured_at,to_jsonb(s)-'payload_hash' FROM thermal_inversion.soil_moisture_readings s WHERE station_id=@id
  UNION ALL SELECT id,'air-humidity',station_id,measured_at,to_jsonb(h)-'payload_hash' FROM thermal_inversion.air_humidity_readings h WHERE station_id=@id
  UNION ALL SELECT id,'atmospheric-pressure',station_id,measured_at,to_jsonb(a)-'payload_hash' FROM thermal_inversion.atmospheric_pressure_readings a WHERE station_id=@id
  UNION ALL SELECT id,'wind-speed',station_id,measured_at,to_jsonb(w)-'payload_hash' FROM thermal_inversion.wind_speed_readings w WHERE station_id=@id
 ) readings ORDER BY measured_at DESC LIMIT @limit
 """;

record TemperatureProfileInput(string StationId,string SurfaceSensorId,string UpperSensorId,double SurfaceTemperatureC,double UpperTemperatureC,DateTimeOffset Timestamp);
record SoilMoistureInput(string StationId,string SensorId,double SoilMoisturePercent,DateTimeOffset Timestamp);
record AirHumidityInput(string StationId,string SensorId,double AirHumidityPercent,DateTimeOffset Timestamp);
record AtmosphericPressureInput(string StationId,string SensorId,double PressureHpa,DateTimeOffset Timestamp);
record WindSpeedInput(string StationId,string SensorId,double WindSpeedMps,DateTimeOffset Timestamp);
record OccurrenceInput(string StationId,string Description,string Severity,string Status,DateTimeOffset Timestamp);
