using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Serialization;
using Microsoft.Data.Sqlite;

var app = WebApplication.CreateBuilder(args).Build();
var cs = new SqliteConnectionStringBuilder { DataSource = Environment.GetEnvironmentVariable("DB_PATH") ?? Path.GetFullPath("../data/inversao_termica.db") }.ToString();
await Db.Init(cs);
app.MapGet("/health/live", () => Results.Ok(new { status = "live" }));
app.MapGet("/health/ready", () => Results.Ok(new { status = "ready" }));
app.MapPost("/api/v1/sensores/{sourceId}/leituras", async (string sourceId, Leitura payload, HttpRequest request) => {
  if(string.IsNullOrWhiteSpace(payload.Fonte?.Id)||string.IsNullOrWhiteSpace(payload.Fonte.Tipo)||string.IsNullOrWhiteSpace(payload.Estacao)||string.IsNullOrWhiteSpace(payload.DataColetada)||payload.Dados is null||!double.TryParse(payload.Dados.TempMin.Replace("°C",""),System.Globalization.CultureInfo.InvariantCulture,out var min)||!double.TryParse(payload.Dados.TempMax.Replace("°C",""),System.Globalization.CultureInfo.InvariantCulture,out var max))return Results.BadRequest(new{erro="Campos obrigatórios ausentes ou temperaturas inválidas"});
  if(request.Headers.TryGetValue("X-Source-Id",out var header)&&header!=payload.Fonte.Id)return Results.BadRequest(new{erro="X-Source-Id diverge de fonte.id"}); if(sourceId!=payload.Fonte.Id)return Results.NotFound(new{erro="A rota deve usar o mesmo sensor de fonte.id"}); return await Db.Save(cs,payload,min,max);
});
app.Run("http://0.0.0.0:"+(Environment.GetEnvironmentVariable("PORT")??"3004"));
record Fonte(string Id,string Tipo,[property:JsonPropertyName("organização")]string? Organizacao); record Dados(string TempMin,string TempMax,double Umidade); record Leitura(Fonte Fonte,string Estacao,string DataColetada,Dados Dados);
static class Db { public static async Task Init(string cs){await using var c=new SqliteConnection(cs);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS ingestoes(id INTEGER PRIMARY KEY AUTOINCREMENT,source_id TEXT NOT NULL,source_type TEXT NOT NULL,source_organization TEXT,collected_at TEXT NOT NULL,received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,payload_hash TEXT NOT NULL UNIQUE,payload_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS leituras_inversao_termica(ingestion_id INTEGER PRIMARY KEY REFERENCES ingestoes(id),estacao TEXT NOT NULL,temperatura_min_c REAL NOT NULL,temperatura_max_c REAL NOT NULL,umidade_percentual REAL NOT NULL);";await q.ExecuteNonQueryAsync();} public static async Task<IResult> Save(string cs,Leitura p,double min,double max){var json=System.Text.Json.JsonSerializer.Serialize(p);var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(json))).ToLowerInvariant();await using var c=new SqliteConnection(cs);await c.OpenAsync();var e=c.CreateCommand();e.CommandText="SELECT id FROM ingestoes WHERE payload_hash=$hash";e.Parameters.AddWithValue("$hash",hash);if(await e.ExecuteScalarAsync() is long old)return Results.Ok(new{status="já recebido",ingestionId=old});await using var tx=(SqliteTransaction)await c.BeginTransactionAsync();try{var i=c.CreateCommand();i.Transaction=tx;i.CommandText="INSERT INTO ingestoes(source_id,source_type,source_organization,collected_at,payload_hash,payload_json) VALUES($id,$type,$org,$date,$hash,$json) RETURNING id";i.Parameters.AddWithValue("$id",p.Fonte.Id);i.Parameters.AddWithValue("$type",p.Fonte.Tipo);i.Parameters.AddWithValue("$org",(object?)p.Fonte.Organizacao??DBNull.Value);i.Parameters.AddWithValue("$date",p.DataColetada);i.Parameters.AddWithValue("$hash",hash);i.Parameters.AddWithValue("$json",json);var id=(long)(await i.ExecuteScalarAsync())!;var r=c.CreateCommand();r.Transaction=tx;r.CommandText="INSERT INTO leituras_inversao_termica VALUES($id,$station,$min,$max,$humidity)";r.Parameters.AddWithValue("$id",id);r.Parameters.AddWithValue("$station",p.Estacao);r.Parameters.AddWithValue("$min",min);r.Parameters.AddWithValue("$max",max);r.Parameters.AddWithValue("$humidity",p.Dados.Umidade);await r.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Created($"/ingestoes/{id}",new{status="recebido",ingestionId=id});}catch(Exception x){await tx.RollbackAsync();return Results.Problem(x.Message,statusCode:500);}}}
