using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Npgsql;

record LocalSeed(string Id, string Nome, string? Endereco, double? Latitude, double? Longitude);
record SensorSeed(string Id, string Tipo, string Organizacao, string LocalId, string Unidade,
    double? LimiteAlerta = null, string OperadorAlerta = ">=", string OrigemDado = "direto",
    double? AlturaInstalacaoMetros = null);
record LocalCadastro(string Id, string Nome, string? Endereco, double? Latitude, double? Longitude);
record SensorCadastro(string Id, string Tipo, string Organizacao, string LocalId, string Unidade,
    double? LimiteAlerta, string? OperadorAlerta, string? OrigemDado, double? AlturaInstalacaoMetros);
record OcorrenciaCadastro(string Origem, string? OrigemId, string LocalId, string Descricao,
    string Severidade, string Status, string DataOcorrencia);
record MeasurementOutcome(IResult Result, long? MeasurementId, string? LocalId, bool Inserted);

static class DomainStore
{
    public static async Task Initialize(string cs, IEnumerable<LocalSeed> locations, IEnumerable<SensorSeed> sensors)
    {
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                CREATE TABLE IF NOT EXISTS locais (
                    id TEXT PRIMARY KEY, nome TEXT NOT NULL, endereco TEXT,
                    latitude DOUBLE PRECISION, longitude DOUBLE PRECISION,
                    criado_em TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
                );
                CREATE TABLE IF NOT EXISTS sensores (
                    id TEXT PRIMARY KEY, tipo TEXT NOT NULL, organizacao TEXT NOT NULL,
                    local_id TEXT NOT NULL REFERENCES locais(id), unidade TEXT NOT NULL,
                    limite_alerta DOUBLE PRECISION, operador_alerta TEXT NOT NULL DEFAULT '>=',
                    origem_dado TEXT NOT NULL DEFAULT 'direto', altura_instalacao_m DOUBLE PRECISION,
                    ativo BOOLEAN NOT NULL DEFAULT TRUE,
                    criado_em TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
                );
                ALTER TABLE sensores ADD COLUMN IF NOT EXISTS altura_instalacao_m DOUBLE PRECISION;
                CREATE TABLE IF NOT EXISTS medicoes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sensor_id TEXT NOT NULL REFERENCES sensores(id),
                    local_id TEXT NOT NULL REFERENCES locais(id), tipo TEXT NOT NULL,
                    data_coletada TEXT NOT NULL, recebido_em TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
                    dados_json TEXT NOT NULL, payload_hash TEXT NOT NULL UNIQUE
                );
                CREATE INDEX IF NOT EXISTS ix_medicoes_tipo_data ON medicoes(tipo, id DESC);
                CREATE TABLE IF NOT EXISTS ocorrencias (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    origem TEXT NOT NULL, origem_id TEXT, local_id TEXT NOT NULL REFERENCES locais(id),
                    descricao TEXT NOT NULL, severidade TEXT NOT NULL, status TEXT NOT NULL,
                    data_ocorrencia TEXT NOT NULL, recebido_em TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
                );
                CREATE TABLE IF NOT EXISTS alertas (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    chave TEXT NOT NULL UNIQUE, medicao_id BIGINT REFERENCES medicoes(id),
                    local_id TEXT NOT NULL REFERENCES locais(id), tipo TEXT NOT NULL,
                    severidade TEXT NOT NULL, mensagem TEXT NOT NULL,
                    criado_em TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
                );
                """;
            await command.ExecuteNonQueryAsync();
        }

        foreach (var location in locations)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                INSERT INTO locais(id,nome,endereco,latitude,longitude)
                VALUES(@id,@nome,@endereco,@latitude,@longitude) ON CONFLICT(id) DO NOTHING
                """;
            command.Parameters.AddWithValue("id", location.Id);
            command.Parameters.AddWithValue("nome", location.Nome);
            command.Parameters.AddWithValue("endereco", (object?)location.Endereco ?? DBNull.Value);
            command.Parameters.AddWithValue("latitude", (object?)location.Latitude ?? DBNull.Value);
            command.Parameters.AddWithValue("longitude", (object?)location.Longitude ?? DBNull.Value);
            await command.ExecuteNonQueryAsync();
        }

        foreach (var sensor in sensors)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                INSERT INTO sensores(id,tipo,organizacao,local_id,unidade,limite_alerta,operador_alerta,origem_dado,altura_instalacao_m)
                VALUES(@id,@tipo,@org,@local,@unidade,@limite,@operador,@origem,@altura)
                ON CONFLICT(id) DO UPDATE SET tipo=EXCLUDED.tipo, organizacao=EXCLUDED.organizacao,
                    local_id=EXCLUDED.local_id, unidade=EXCLUDED.unidade, limite_alerta=EXCLUDED.limite_alerta,
                    operador_alerta=EXCLUDED.operador_alerta, origem_dado=EXCLUDED.origem_dado,
                    altura_instalacao_m=EXCLUDED.altura_instalacao_m
                """;
            command.Parameters.AddWithValue("id", sensor.Id);
            command.Parameters.AddWithValue("tipo", sensor.Tipo);
            command.Parameters.AddWithValue("org", sensor.Organizacao);
            command.Parameters.AddWithValue("local", sensor.LocalId);
            command.Parameters.AddWithValue("unidade", sensor.Unidade);
            command.Parameters.AddWithValue("limite", (object?)sensor.LimiteAlerta ?? DBNull.Value);
            command.Parameters.AddWithValue("operador", sensor.OperadorAlerta);
            command.Parameters.AddWithValue("origem", sensor.OrigemDado);
            command.Parameters.AddWithValue("altura", (object?)sensor.AlturaInstalacaoMetros ?? DBNull.Value);
            await command.ExecuteNonQueryAsync();
        }
    }

    public static IResult? ValidateSource(HttpRequest request, string sensorId)
    {
        if (request.Headers.TryGetValue("X-Source-Id", out var header) && header != sensorId)
            return Results.BadRequest(new { erro = "X-Source-Id diverge do sensorId da rota" });
        return null;
    }

    public static async Task<MeasurementOutcome> SaveMeasurement<T>(string cs, string sensorId,
        string expectedType, string collectedAt, string? requestedLocation, T data, double? alertValue = null)
    {
        if (string.IsNullOrWhiteSpace(collectedAt))
            return new(Results.BadRequest(new { erro = "dataColetada é obrigatória" }), null, null, false);

        var dataJson = JsonSerializer.Serialize(data, new JsonSerializerOptions(JsonSerializerDefaults.Web));
        var hashInput = $"{sensorId}|{expectedType}|{collectedAt}|{dataJson}";
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(hashInput))).ToLowerInvariant();
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        try
        {
            string actualType;
            string registeredLocation;
            string unit;
            double? threshold;
            string alertOperator;
            await using (var sensor = connection.CreateCommand())
            {
                sensor.Transaction = transaction;
                sensor.CommandText = """
                    SELECT tipo,local_id,unidade,limite_alerta,operador_alerta
                    FROM sensores WHERE id=@id AND ativo=TRUE
                    """;
                sensor.Parameters.AddWithValue("id", sensorId);
                await using var reader = await sensor.ExecuteReaderAsync();
                if (!await reader.ReadAsync())
                    return new(Results.NotFound(new { erro = "Sensor não cadastrado ou inativo", sensorId }), null, null, false);
                actualType = reader.GetString(0);
                registeredLocation = reader.GetString(1);
                unit = reader.GetString(2);
                threshold = reader.IsDBNull(3) ? null : reader.GetDouble(3);
                alertOperator = reader.GetString(4);
            }

            if (!string.Equals(actualType, expectedType, StringComparison.OrdinalIgnoreCase))
                return new(Results.BadRequest(new { erro = "Tipo do sensor incompatível com a rota", esperado = expectedType, cadastrado = actualType }), null, null, false);

            var location = string.IsNullOrWhiteSpace(requestedLocation) ? registeredLocation : requestedLocation;
            await using var insert = connection.CreateCommand();
            insert.Transaction = transaction;
            insert.CommandText = """
                INSERT INTO medicoes(sensor_id,local_id,tipo,data_coletada,dados_json,payload_hash)
                VALUES(@sensor,@local,@tipo,@data,@dados,@hash)
                ON CONFLICT(payload_hash) DO NOTHING RETURNING id
                """;
            insert.Parameters.AddWithValue("sensor", sensorId);
            insert.Parameters.AddWithValue("local", location);
            insert.Parameters.AddWithValue("tipo", expectedType);
            insert.Parameters.AddWithValue("data", collectedAt);
            insert.Parameters.AddWithValue("dados", dataJson);
            insert.Parameters.AddWithValue("hash", hash);
            var inserted = await insert.ExecuteScalarAsync();
            if (inserted is null)
            {
                await using var existing = connection.CreateCommand();
                existing.Transaction = transaction;
                existing.CommandText = "SELECT id,local_id FROM medicoes WHERE payload_hash=@hash";
                existing.Parameters.AddWithValue("hash", hash);
                await using var reader = await existing.ExecuteReaderAsync();
                await reader.ReadAsync();
                var oldId = reader.GetInt64(0);
                var oldLocation = reader.GetString(1);
                await transaction.CommitAsync();
                return new(Results.Ok(new { status = "já recebido", medicaoId = oldId }), oldId, oldLocation, false);
            }

            var id = (long)inserted;
            if (threshold is not null && alertValue is not null && IsAlert(alertValue.Value, threshold.Value, alertOperator))
            {
                await using var alert = connection.CreateCommand();
                alert.Transaction = transaction;
                alert.CommandText = """
                    INSERT INTO alertas(chave,medicao_id,local_id,tipo,severidade,mensagem)
                    VALUES(@chave,@medicao,@local,@tipo,'alta',@mensagem) ON CONFLICT(chave) DO NOTHING
                    """;
                alert.Parameters.AddWithValue("chave", $"medicao-{id}");
                alert.Parameters.AddWithValue("medicao", id);
                alert.Parameters.AddWithValue("local", location);
                alert.Parameters.AddWithValue("tipo", expectedType);
                alert.Parameters.AddWithValue("mensagem", $"Valor {alertValue.Value} {unit} atingiu o limite configurado ({alertOperator} {threshold.Value} {unit}).");
                await alert.ExecuteNonQueryAsync();
            }

            await transaction.CommitAsync();
            return new(Results.Created($"/api/v2/medicoes/{id}", new { status = "recebido", medicaoId = id }), id, location, true);
        }
        catch (PostgresException error) when (error.SqlState == "23503")
        {
            await transaction.RollbackAsync();
            return new(Results.BadRequest(new { erro = "Local informado não está cadastrado" }), null, null, false);
        }
        catch
        {
            await transaction.RollbackAsync();
            return new(Results.Problem("Falha ao persistir a medição", statusCode: 500), null, null, false);
        }
    }

    public static void MapCommonRoutes(WebApplication app, string cs, IReadOnlySet<string> allowedSensorTypes)
    {
        app.MapPost("/api/v2/locais", async (LocalCadastro payload) =>
        {
            if (string.IsNullOrWhiteSpace(payload.Id) || string.IsNullOrWhiteSpace(payload.Nome) ||
                payload.Latitude is < -90 or > 90 || payload.Longitude is < -180 or > 180)
                return Results.BadRequest(new { erro = "Local inválido" });
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = """
                INSERT INTO locais(id,nome,endereco,latitude,longitude)
                VALUES(@id,@nome,@endereco,@latitude,@longitude)
                ON CONFLICT(id) DO NOTHING RETURNING id
                """;
            command.Parameters.AddWithValue("id", payload.Id);
            command.Parameters.AddWithValue("nome", payload.Nome);
            command.Parameters.AddWithValue("endereco", (object?)payload.Endereco ?? DBNull.Value);
            command.Parameters.AddWithValue("latitude", (object?)payload.Latitude ?? DBNull.Value);
            command.Parameters.AddWithValue("longitude", (object?)payload.Longitude ?? DBNull.Value);
            return await command.ExecuteScalarAsync() is null
                ? Results.Conflict(new { erro = "Já existe um local com esse id" })
                : Results.Created($"/api/v2/locais/{payload.Id}", payload);
        });

        app.MapGet("/api/v2/locais", async () =>
        {
            var items = new List<object>();
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT id,nome,endereco,latitude,longitude,criado_em FROM locais ORDER BY id";
            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
                items.Add(new { id = reader.GetString(0), nome = reader.GetString(1), endereco = reader.IsDBNull(2) ? null : reader.GetString(2), latitude = reader.IsDBNull(3) ? (double?)null : reader.GetDouble(3), longitude = reader.IsDBNull(4) ? (double?)null : reader.GetDouble(4), criadoEm = reader.GetDateTime(5) });
            return Results.Ok(items);
        });

        app.MapPost("/api/v2/sensores", async (SensorCadastro payload) =>
        {
            var sourceKind = payload.OrigemDado ?? "direto";
            var alertOperator = payload.OperadorAlerta ?? ">=";
            if (string.IsNullOrWhiteSpace(payload.Id) || string.IsNullOrWhiteSpace(payload.Tipo) ||
                string.IsNullOrWhiteSpace(payload.Organizacao) || string.IsNullOrWhiteSpace(payload.LocalId) ||
                string.IsNullOrWhiteSpace(payload.Unidade) || !allowedSensorTypes.Contains(payload.Tipo) ||
                sourceKind is not ("direto" or "derivado") || alertOperator is not (">=" or "<="))
                return Results.BadRequest(new { erro = "Cadastro de sensor inválido", tiposPermitidos = allowedSensorTypes });
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = """
                INSERT INTO sensores(id,tipo,organizacao,local_id,unidade,limite_alerta,operador_alerta,origem_dado,altura_instalacao_m)
                VALUES(@id,@tipo,@org,@local,@unidade,@limite,@operador,@origem,@altura)
                ON CONFLICT(id) DO NOTHING RETURNING id
                """;
            command.Parameters.AddWithValue("id", payload.Id);
            command.Parameters.AddWithValue("tipo", payload.Tipo);
            command.Parameters.AddWithValue("org", payload.Organizacao);
            command.Parameters.AddWithValue("local", payload.LocalId);
            command.Parameters.AddWithValue("unidade", payload.Unidade);
            command.Parameters.AddWithValue("limite", (object?)payload.LimiteAlerta ?? DBNull.Value);
            command.Parameters.AddWithValue("operador", alertOperator);
            command.Parameters.AddWithValue("origem", sourceKind);
            command.Parameters.AddWithValue("altura", (object?)payload.AlturaInstalacaoMetros ?? DBNull.Value);
            try
            {
                return await command.ExecuteScalarAsync() is null
                    ? Results.Conflict(new { erro = "Já existe um sensor com esse id" })
                    : Results.Created($"/api/v2/sensores/{payload.Id}", payload);
            }
            catch (PostgresException error) when (error.SqlState == "23503")
            {
                return Results.BadRequest(new { erro = "O localId informado não existe" });
            }
        });

        app.MapGet("/api/v2/sensores", async () =>
        {
            var items = new List<object>();
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT id,tipo,organizacao,local_id,unidade,limite_alerta,operador_alerta,origem_dado,altura_instalacao_m,ativo FROM sensores ORDER BY id";
            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
                items.Add(new { id = reader.GetString(0), tipo = reader.GetString(1), organizacao = reader.GetString(2), localId = reader.GetString(3), unidade = reader.GetString(4), limiteAlerta = reader.IsDBNull(5) ? (double?)null : reader.GetDouble(5), operadorAlerta = reader.GetString(6), origemDado = reader.GetString(7), alturaInstalacaoMetros = reader.IsDBNull(8) ? (double?)null : reader.GetDouble(8), ativo = reader.GetBoolean(9) });
            return Results.Ok(items);
        });

        app.MapGet("/api/v2/medicoes", async (int? limite, string? tipo, string? sensorId) =>
            await ListMeasurements(cs, limite, tipo, sensorId));
        app.MapGet("/api/v2/medicoes/{id:long}", async (long id) => await GetMeasurement(cs, id));

        app.MapPost("/api/v2/ocorrencias", async (OcorrenciaCadastro payload) =>
        {
            if (string.IsNullOrWhiteSpace(payload.Origem) || string.IsNullOrWhiteSpace(payload.LocalId) ||
                string.IsNullOrWhiteSpace(payload.Descricao) || string.IsNullOrWhiteSpace(payload.Severidade) ||
                string.IsNullOrWhiteSpace(payload.Status) || string.IsNullOrWhiteSpace(payload.DataOcorrencia))
                return Results.BadRequest(new { erro = "Campos obrigatórios ausentes" });
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = """
                INSERT INTO ocorrencias(origem,origem_id,local_id,descricao,severidade,status,data_ocorrencia)
                VALUES(@origem,@origemId,@local,@descricao,@severidade,@status,@data) RETURNING id
                """;
            command.Parameters.AddWithValue("origem", payload.Origem);
            command.Parameters.AddWithValue("origemId", (object?)payload.OrigemId ?? DBNull.Value);
            command.Parameters.AddWithValue("local", payload.LocalId);
            command.Parameters.AddWithValue("descricao", payload.Descricao);
            command.Parameters.AddWithValue("severidade", payload.Severidade);
            command.Parameters.AddWithValue("status", payload.Status);
            command.Parameters.AddWithValue("data", payload.DataOcorrencia);
            try
            {
                var id = (long)(await command.ExecuteScalarAsync())!;
                return Results.Created($"/api/v2/ocorrencias/{id}", new { status = "recebida", ocorrenciaId = id });
            }
            catch (PostgresException error) when (error.SqlState == "23503")
            {
                return Results.BadRequest(new { erro = "O localId informado não existe" });
            }
        });

        app.MapGet("/api/v2/ocorrencias", async (int? limite) =>
        {
            var valid = ValidateLimit(limite);
            if (valid is not null) return valid;
            var items = new List<object>();
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT id,origem,origem_id,local_id,descricao,severidade,status,data_ocorrencia,recebido_em FROM ocorrencias ORDER BY id DESC LIMIT @limite";
            command.Parameters.AddWithValue("limite", limite ?? 100);
            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
                items.Add(new { id = reader.GetInt64(0), origem = reader.GetString(1), origemId = reader.IsDBNull(2) ? null : reader.GetString(2), localId = reader.GetString(3), descricao = reader.GetString(4), severidade = reader.GetString(5), status = reader.GetString(6), dataOcorrencia = reader.GetString(7), recebidoEm = reader.GetDateTime(8) });
            return Results.Ok(items);
        });

        app.MapGet("/api/v2/alertas", async (int? limite) =>
        {
            var valid = ValidateLimit(limite);
            if (valid is not null) return valid;
            var items = new List<object>();
            await using var connection = new NpgsqlConnection(cs);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT id,medicao_id,local_id,tipo,severidade,mensagem,criado_em FROM alertas ORDER BY id DESC LIMIT @limite";
            command.Parameters.AddWithValue("limite", limite ?? 100);
            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
                items.Add(new { id = reader.GetInt64(0), medicaoId = reader.IsDBNull(1) ? (long?)null : reader.GetInt64(1), localId = reader.GetString(2), tipo = reader.GetString(3), severidade = reader.GetString(4), mensagem = reader.GetString(5), criadoEm = reader.GetDateTime(6) });
            return Results.Ok(items);
        });
    }

    static async Task<IResult> ListMeasurements(string cs, int? limit, string? type, string? sensorId)
    {
        var valid = ValidateLimit(limit);
        if (valid is not null) return valid;
        var conditions = new List<string>();
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        if (!string.IsNullOrWhiteSpace(type)) { conditions.Add("tipo=@tipo"); command.Parameters.AddWithValue("tipo", type); }
        if (!string.IsNullOrWhiteSpace(sensorId)) { conditions.Add("sensor_id=@sensor"); command.Parameters.AddWithValue("sensor", sensorId); }
        var where = conditions.Count == 0 ? "" : "WHERE " + string.Join(" AND ", conditions);
        command.CommandText = $"SELECT id,sensor_id,local_id,tipo,data_coletada,recebido_em,dados_json FROM medicoes {where} ORDER BY id DESC LIMIT @limite";
        command.Parameters.AddWithValue("limite", limit ?? 100);
        var items = new List<object>();
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            items.Add(MeasurementObject(reader));
        return Results.Ok(items);
    }

    static async Task<IResult> GetMeasurement(string cs, long id)
    {
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT id,sensor_id,local_id,tipo,data_coletada,recebido_em,dados_json FROM medicoes WHERE id=@id";
        command.Parameters.AddWithValue("id", id);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? Results.Ok(MeasurementObject(reader)) : Results.NotFound();
    }

    public static async Task<double?> GetSensorInstallationHeight(string cs, string sensorId)
    {
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT altura_instalacao_m FROM sensores WHERE id=@id";
        command.Parameters.AddWithValue("id", sensorId);
        var value = await command.ExecuteScalarAsync();
        return value is null or DBNull ? null : Convert.ToDouble(value);
    }

    static object MeasurementObject(NpgsqlDataReader reader) => new
    {
        id = reader.GetInt64(0), sensorId = reader.GetString(1), localId = reader.GetString(2),
        tipo = reader.GetString(3), dataColetada = reader.GetString(4), recebidoEm = reader.GetDateTime(5),
        dados = JsonSerializer.Deserialize<JsonElement>(reader.GetString(6))
    };

    static IResult? ValidateLimit(int? limit) => limit is < 1 or > 1000
        ? Results.BadRequest(new { erro = "limite deve estar entre 1 e 1000" }) : null;

    static bool IsAlert(double value, double threshold, string operation) =>
        operation == "<=" ? value <= threshold : value >= threshold;
}
