using System.Security.Cryptography;
using System.Text;
using Npgsql;

static class PostgresStore
{
    public static async Task Initialize(string cs, string table, string columns)
    {
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"""
            CREATE TABLE IF NOT EXISTS ingestoes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_id TEXT NOT NULL, source_type TEXT NOT NULL, source_organization TEXT,
                collected_at TEXT NOT NULL,
                received_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
                payload_hash TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS {table} (ingestion_id BIGINT PRIMARY KEY REFERENCES ingestoes(id), {columns});
            """;
        await command.ExecuteNonQueryAsync();
    }

    public static async Task<IResult> Save<T>(string cs, string sourceId, string sourceType,
        string? organization, string collectedAt, T payload, string table, string names,
        string values, Action<NpgsqlCommand> add)
    {
        var json = System.Text.Json.JsonSerializer.Serialize(payload);
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(json))).ToLowerInvariant();
        await using var connection = new NpgsqlConnection(cs);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        try
        {
            await using var ingest = connection.CreateCommand();
            ingest.Transaction = transaction;
            ingest.CommandText = """
                INSERT INTO ingestoes(source_id,source_type,source_organization,collected_at,payload_hash,payload_json)
                VALUES(@id,@type,@org,@date,@hash,@json)
                ON CONFLICT(payload_hash) DO NOTHING RETURNING id
                """;
            ingest.Parameters.AddWithValue("id", sourceId);
            ingest.Parameters.AddWithValue("type", sourceType);
            ingest.Parameters.AddWithValue("org", (object?)organization ?? DBNull.Value);
            ingest.Parameters.AddWithValue("date", collectedAt);
            ingest.Parameters.AddWithValue("hash", hash);
            ingest.Parameters.AddWithValue("json", json);
            var inserted = await ingest.ExecuteScalarAsync();
            if (inserted is null)
            {
                await using var existing = connection.CreateCommand();
                existing.Transaction = transaction;
                existing.CommandText = "SELECT id FROM ingestoes WHERE payload_hash=@hash";
                existing.Parameters.AddWithValue("hash", hash);
                var oldId = (long)(await existing.ExecuteScalarAsync())!;
                await transaction.CommitAsync();
                return Results.Ok(new { status = "já recebido", ingestionId = oldId });
            }

            var id = (long)inserted;
            await using var reading = connection.CreateCommand();
            reading.Transaction = transaction;
            reading.CommandText = $"INSERT INTO {table}(ingestion_id,{names}) VALUES(@id,{values})";
            reading.Parameters.AddWithValue("id", id);
            add(reading);
            await reading.ExecuteNonQueryAsync();
            await transaction.CommitAsync();
            return Results.Created($"/ingestoes/{id}", new { status = "recebido", ingestionId = id });
        }
        catch
        {
            await transaction.RollbackAsync();
            return Results.Problem("Falha ao persistir a leitura", statusCode: 500);
        }
    }
}
