using Npgsql;

var app=WebApplication.CreateBuilder(args).Build();
var cs=Environment.GetEnvironmentVariable("DATABASE_URL")??throw new InvalidOperationException("DATABASE_URL não configurada");
await SharedApi.Initialize(cs,"""
CREATE SCHEMA IF NOT EXISTS overflow;
CREATE TABLE IF NOT EXISTS overflow.monitoring_points(id TEXT PRIMARY KEY,name TEXT NOT NULL,area_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS overflow.sensors(id TEXT PRIMARY KEY,monitoring_point_id TEXT NOT NULL REFERENCES overflow.monitoring_points(id),owner_name TEXT NOT NULL,description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS overflow.water_level_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,monitoring_point_id TEXT NOT NULL REFERENCES overflow.monitoring_points(id),sensor_id TEXT NOT NULL REFERENCES overflow.sensors(id),water_level_cm DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS overflow.rainfall_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,monitoring_point_id TEXT NOT NULL REFERENCES overflow.monitoring_points(id),sensor_id TEXT NOT NULL REFERENCES overflow.sensors(id),rainfall_mm DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS overflow.flow_rate_readings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,monitoring_point_id TEXT NOT NULL REFERENCES overflow.monitoring_points(id),sensor_id TEXT NOT NULL REFERENCES overflow.sensors(id),flow_rate_m3s DOUBLE PRECISION NOT NULL,measured_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),payload_hash TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS overflow.alerts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reading_type TEXT NOT NULL,reading_id BIGINT NOT NULL,severity TEXT NOT NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),UNIQUE(reading_type,reading_id,message));
INSERT INTO overflow.monitoring_points VALUES('river-central','Córrego Central','area-central') ON CONFLICT DO NOTHING;
INSERT INTO overflow.sensors VALUES
 ('japa-overflow-01','river-central','Japa','Nível da água, precipitação e vazão'),
 ('mat-overflow-01','river-central','Mat','Nível do córrego, chuva acumulada e pressão da coluna de água'),
 ('tanke-overflow-01','river-central','Tanke','Nível do córrego e chuva acumulada')
 ON CONFLICT DO NOTHING;
""");

app.MapPost("/api/v1/overflow/water-level",async(WaterLevelInput p)=>{
 if(p.WaterLevelCm<0)return Results.BadRequest(new{erro="waterLevelCm não pode ser negativo"});
 return await Save("water_level_readings","water_level_cm","water-level",new(p.MonitoringPointId,p.SensorId,p.WaterLevelCm,p.Timestamp),p.WaterLevelCm>=200,"Nível de água elevado");
});
app.MapPost("/api/v1/overflow/rainfall",async(RainfallInput p)=>{
 if(p.RainfallMm<0)return Results.BadRequest(new{erro="rainfallMm não pode ser negativo"});
 return await Save("rainfall_readings","rainfall_mm","rainfall",new(p.MonitoringPointId,p.SensorId,p.RainfallMm,p.Timestamp),p.RainfallMm>=50,"Precipitação acumulada elevada");
});
app.MapPost("/api/v1/overflow/flow-rate",async(FlowRateInput p)=>{
 if(p.FlowRateM3s<0)return Results.BadRequest(new{erro="flowRateM3s não pode ser negativo"});
 return await Save("flow_rate_readings","flow_rate_m3s","flow-rate",new(p.MonitoringPointId,p.SensorId,p.FlowRateM3s,p.Timestamp),p.FlowRateM3s>=100,"Vazão elevada");
});
app.MapGet("/api/v1/overflow/water-level",(int? limit)=>List("water_level_readings",limit));
app.MapGet("/api/v1/overflow/rainfall",(int? limit)=>List("rainfall_readings",limit));
app.MapGet("/api/v1/overflow/flow-rate",(int? limit)=>List("flow_rate_readings",limit));
app.MapGet("/api/v1/overflow/sensors",()=>SharedApi.Query(cs,"SELECT * FROM overflow.sensors ORDER BY id"));
app.MapGet("/api/v1/overflow/monitoring-points",()=>SharedApi.Query(cs,"SELECT * FROM overflow.monitoring_points ORDER BY id"));
app.MapGet("/api/v1/overflow/monitoring-points/{id}/readings",(string id,int? limit)=>SharedApi.Query(cs,Combined(false),("id",id),("limit",SharedApi.Limit(limit))));
app.MapGet("/api/v1/overflow/monitoring-points/{id}/latest",(string id)=>SharedApi.Query(cs,Combined(true),("id",id),("limit",3)));
app.MapGet("/api/v1/overflow/alerts",(int? limit)=>SharedApi.Query(cs,"SELECT * FROM overflow.alerts ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit))));
app.MapGet("/",()=>Results.Redirect("/api/v1/overflow/monitoring-points"));
app.MapGet("/health/live",()=>Results.Ok(new{status="live"}));
app.MapGet("/health/ready",()=>SharedApi.Ready(cs,"overflow"));
app.Run("http://0.0.0.0:"+(Environment.GetEnvironmentVariable("PORT")??"3002"));

async Task<IResult> Save(string table,string column,string type,MeasureInput p,bool alert,string message)
{
 try{
  var saved=await SharedApi.Insert(cs,$"overflow.{table}",new Dictionary<string,object?>{{"monitoring_point_id",p.MonitoringPointId},{"sensor_id",p.SensorId},{column,p.Value},{"measured_at",p.Timestamp}},new{type,p.MonitoringPointId,p.SensorId,p.Value,p.Timestamp});
  if(saved.Inserted&&alert){
   await using var connection=new NpgsqlConnection(cs);await connection.OpenAsync();await using var command=connection.CreateCommand();
   command.CommandText="INSERT INTO overflow.alerts(reading_type,reading_id,severity,message) VALUES(@type,@id,'high',@message) ON CONFLICT DO NOTHING";
   command.Parameters.AddWithValue("type",type);command.Parameters.AddWithValue("id",saved.Id);command.Parameters.AddWithValue("message",message);await command.ExecuteNonQueryAsync();
  }
  return saved.Inserted?Results.Created($"/api/v1/overflow/{type}/{saved.Id}",new{id=saved.Id,status="persisted"}):Results.Ok(new{id=saved.Id,status="already received"});
 }catch(PostgresException e)when(e.SqlState=="23503"){return Results.BadRequest(new{erro="MonitoringPointId ou SensorId não cadastrado"});}
}
Task<List<System.Text.Json.JsonElement>> List(string table,int? limit)=>SharedApi.Query(cs,$"SELECT * FROM overflow.{table} ORDER BY id DESC LIMIT @limit",("limit",SharedApi.Limit(limit)));
static string Combined(bool latest)=>$"""
 SELECT * FROM (
  SELECT id,'water-level' reading_type,monitoring_point_id,sensor_id,water_level_cm value,measured_at FROM overflow.water_level_readings WHERE monitoring_point_id=@id
  UNION ALL SELECT id,'rainfall',monitoring_point_id,sensor_id,rainfall_mm,measured_at FROM overflow.rainfall_readings WHERE monitoring_point_id=@id
  UNION ALL SELECT id,'flow-rate',monitoring_point_id,sensor_id,flow_rate_m3s,measured_at FROM overflow.flow_rate_readings WHERE monitoring_point_id=@id
 ) readings ORDER BY measured_at DESC LIMIT @limit
 """;

record MeasureInput(string MonitoringPointId,string SensorId,double Value,DateTimeOffset Timestamp);
record WaterLevelInput(string MonitoringPointId,string SensorId,double WaterLevelCm,DateTimeOffset Timestamp);
record RainfallInput(string MonitoringPointId,string SensorId,double RainfallMm,DateTimeOffset Timestamp);
record FlowRateInput(string MonitoringPointId,string SensorId,double FlowRateM3s,DateTimeOffset Timestamp);
